name: inception

services:
  adminer:
    container_name: adminer
    build:
      context: requirements/bonus/adminer
    init: true
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network  
  astro:
    container_name: astro
    build:
      context: requirements/bonus/astro
    init: true
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
  ftp:
    container_name: ftp
    build:
      context: requirements/bonus/ftp
    env_file:
      - .env
    init: true
    restart: unless-stopped
    volumes:
      - wordpress_data:/ftp/data
    networks:
      - inception_network
    ports:
      - "21:21"
      - 21000-21010:21000-21010
  lounge:
    container_name: lounge
    build:
      context: requirements/bonus/lounge
    init: true
    restart: unless-stopped
    volumes:
      - lounge_data:/var/opt/thelounge
    networks:
      - inception_network
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    env_file:
      - .env
    init: true
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    ports:
      - 443:443
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file:
      - .env
    init: true
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception_network
  redis:
    container_name: redis
    build:
      context: requirements/bonus/redis
    init: true
    restart: unless-stopped
    volumes:
      - redis_cache:/data
    networks:
      - inception_network
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    init: true
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
    name: inception_network
  
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: volumes/wordpress
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: volumes/mariadb
  redis_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: volumes/redis
  lounge_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: volumes/lounge
